name: Update Trivia Daily

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-trivia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Trivia Data from Google Sheets
        run: |
          curl -o questions.json "https://docs.google.com/spreadsheets/d/e/2PACX-1vTyVu1etyews0_g-xZB3maofkFmk_SMCwt1vOUEqZpaMGZtF6ikUS9v6dhw9JA7aj2OWajIET0lr6Ij/pub?output=csv"

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add questions.json
          git commit -m "Update trivia questions" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main


      - name: Trigger Netlify Deployment
        run: |
          curl -X POST -d '{}' "https://api.netlify.com/build_hooks/6805623996d913c0a172a6c0"
